### ISSUE TITLE
The popup disappears too quickly

### ISSUE THREAD

**Issue by kalugny** [ubershmekel/show-js-errors#1]
The user should have enough time to process and copy-paste the error

**Comment by nickforddev** [comment]
Even better would be: 

1. Add a small dismiss/close button
1. Stop the timeout for hiding the toast if the mouse rolls over the toast.
1. Restart the timeout for hiding the toast if the mouse exits the area.

**Comment by ubershmekel** [comment]
Should be fixed in e18191ad4c9f79ba3a841fbe46ad158beff00902 thanks!
